version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=your_mongodb_uri
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
    networks:
      - taleem-network

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    networks:
      - taleem-network

  mongo:
    image: mongo
    container_name: taleem-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - taleem-network

volumes:
  mongo-data:

networks:
  taleem-network:
    driver: bridge
